import type {Metadata} from 'next';
import {Outfit} from 'next/font/google';
import './globals.css';
import './index.scss';
import {ThemeProvider} from '@/components/Theme/ThemeProvider/ThemeProvider';

const outfit = Outfit({
	variable: '--font-outfit',
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Home || DevRabbani',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${outfit.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
