import type {Metadata} from 'next';
import {Outfit} from 'next/font/google';
import './globals.css';
import './index.scss';

const outfit = Outfit({
	variable: '--font-outfit',
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Home || DevRabbani',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${outfit.variable} antialiased`}>{children}</body>
		</html>
	);
}
